set(TestSources
    test/src/BasicTypesTest.cpp
    test/src/BitLibTest.cpp
    test/src/EndianTest.cpp
    test/src/MolLookupTest.cpp
    test/src/CircuitTester.cpp
    test/src/PSFParserTest.cpp
)

set(TestHeaders

)

set(GOMCSources
    src/PDBSetup.cpp
    src/MolSetup.cpp
    lib/AlphaNum.cpp
    src/BondAdjacencyList.cpp
    src/ConfigSetup.cpp
    src/FFSetup.cpp
    src/FFConst.cpp
    src/Reader.cpp
    lib/CircuitFinder.cpp
    src/InputFileReader.cpp
    lib/FloydWarshallCycle.cpp
    lib/DCDParser/dcdplugin.cpp
)

set(GOMCHeaders
    src/PDBSetup.h
    src/MolSetup.h
    lib/AlphaNum.h
    src/BondAdjacencyList.h
    src/ConfigSetup.h
    src/FFSetup.h
    src/FFConst.h
    src/Reader.h
    lib/CircuitFinder.h
    src/InputFileReader.h
    lib/FloydWarshallCycle.h
    lib/DCDParser/dcdplugin.h
    lib/DCDParser/endianswap.h
    lib/DCDParser/fastio.h
    lib/DCDParser/largefiles.h
    lib/DCDParser/molfile_plugin.h
    lib/DCDParser/vmdplugin.h
    lib/DCDParser/include/libmolfile_plugin.h
    lib/DCDParser/include/molfile_plugin.h
    lib/DCDParser/include/vmdplugin.h
)