set(sources
   src/BoxDimensions.cpp
   src/BoxDimensionsNonOrth.cpp
   src/CellList.cpp
   src/ConfigSetup.cpp
   src/ConsoleOutput.cpp
   src/Coordinates.cpp
   src/CPUSide.cpp
   src/CalculateEnergy.cpp
   src/CheckpointOutput.cpp
   src/CheckpointSetup.cpp
   src/Ewald.cpp
   src/EwaldCached.cpp
   src/FFConst.cpp
   src/FFDihedrals.cpp
   src/FFParticle.cpp
   src/FFSetup.cpp
   src/Forcefield.cpp
   src/Geometry.cpp
   src/InputFileReader.cpp
   src/Main.cpp
   src/MoleculeKind.cpp
   src/MoleculeLookup.cpp
   src/Molecules.cpp
   src/MolSetup.cpp
   src/MoveSettings.cpp
   src/NoEwald.cpp
   src/OutConst.cpp
   src/OutputVars.cpp
   src/PDBSetup.cpp
   src/PDBOutput.cpp
   src/PRNGSetup.cpp
   src/PSFOutput.cpp
   src/Reader.cpp
   src/Simulation.cpp
   src/StaticVals.cpp
   src/System.cpp)

set(headers
   src/BoxDimensions.h
   src/BoxDimensionsNonOrth.h
   src/CalculateEnergy.h
   src/CellList.h
   src/CheckpointOutput.h
   src/CheckpointSetup.h
   src/Clock.h
   src/COM.h
   src/ConfigSetup.h
   src/ConsoleOutput.h
   src/ConstField.h
   src/Coordinates.h
   src/CoordinateSetup.h
   src/CPUSide.h
   src/EnergyTypes.h
   src/EnsemblePreprocessor.h
   src/Ewald.h
   src/EwaldCached.h  
   src/FFAngles.h
   src/FFBonds.h
   src/FFConst.h
   src/FFDihedrals.h
   src/FFParticle.h
   src/FFSetup.h
   src/FixedWidthReader.h
   src/Forcefield.h
   src/FxdWidthWrtr.h
   src/Geometry.h
   src/InputAbstracts.h
   src/InputFileReader.h
   src/MersenneTwister.h
   src/MoleculeKind.h
   src/MoleculeLookup.h
   src/Molecules.h
   src/MolPick.h
   src/MolSetup.h
   src/MoveConst.h
   src/MoveSettings.h
   src/NoEwald.h
   src/OutConst.h
   src/OutputAbstracts.h
   src/OutputVars.h
   src/PDBConst.h
   src/PDBOutput.h
   src/PDBSetup.h
   src/PRNG.h
   src/PRNGSetup.h
   src/PSFOutput.h
   src/Reader.h
   src/SeedReader.h
   src/Setup.h
   src/SimEventFrequency.h
   src/Simulation.h
   src/StaticVals.h
   src/SubdividedArray.h
   src/System.h
   src/TransformMatrix.h
   src/Writer.h
   src/XYZArray.h
   src/moves/MoveBase.h
   src/moves/MultiParticle.h
   src/moves/Rotation.h
   src/moves/Translate.h
   src/moves/VolumeTransfer.h)

set(libHeaders
   lib/BasicTypes.h
   lib/BitLib.h
   lib/GeomLib.h
   lib/NumLib.h
   lib/StrLib.h
   lib/StrStrmLib.h
   lib/VectorLib.h
   lib/FloydWarshallCycle.h)

set(libSources
    lib/FloydWarshallCycle.cpp)

set(cudaHeaders
    src/GPU/ConstantDefinitionsCUDAKernel.cuh
    src/GPU/CalculateMinImageCUDAKernel.cuh
    src/GPU/CalculateEnergyCUDAKernel.cuh
    src/GPU/CalculateForceCUDAKernel.cuh
    src/GPU/CalculateEwaldCUDAKernel.cuh
    src/GPU/VariablesCUDA.cuh)

set(cudaSources
    src/GPU/CalculateEnergyCUDAKernel.cu
    src/GPU/CalculateForceCUDAKernel.cu
    src/GPU/CalculateEwaldCUDAKernel.cu
    src/GPU/ConstantDefinitionsCUDAKernel.cu)

source_group("Header Files" FILES ${headers})
source_group("Lib Headers" FILES ${libHeaders})
source_group("CUDA Header Files" FILES ${cudaHeaders})
source_group("CUDA Source Files" FILES ${cudaSources})
